name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs everyday at 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true                     
          SHOW_TIMEZONE: true                  
          SHOW_OS: true                        
          SHOW_COMMIT: true                    
          SHOW_PROJECTS: true                  
          SHOW_EDITORS: true                   
          SHOW_LANGUAGE: true                  
          SHOW_LOC_CHART: true                 
          SHOW_DAYS_OF_WEEK: true              
          SHOW_PROFILE_VIEWS: false            
          SHOW_SHORT_INFO: true                
          COMMIT_MSG: "📊 Updated WakaTime Stats in README"
